### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by RancidRocket** [giabao141104/dotfiles#1]
Hello, i am really quite new to dwm, and i was wondering, where do i put the files in the dwm folder? i know you have to edit the source code and recompile when you are configuring it, but other than that, ive got no clue where anything else goes. I've put the contents of the config/ file into my .config, i've compiled and installed the contents of suckless/ but its dwm/ icons/ and scripts/ that i have no idea what to do with. can i please have some help?

**Comment by giabao141104** [comment]
You shouldn't have done that as I don't really know how to organize my files, so the folder names/structure don't really make much sense. Furthermore I made this repo just for backing up my personal dotfiles and for people who are interested in any specific ?feature? of my system to use it as reference.

Some explanations:
dwm/ is where all the script that I bound to some keybinds in config.h
icons/ is just folder for all of the icons I made for dunst (notification daemon) so ignore this
scripts/ are some scripts that do some specific things
Remember to change the directories in my files to match with your system. Like, I put all the scripts under dwm/ in ~/.bin/ (you can see that in config.h), you pulled my repo so yours maybe in ~/github/dotfiles/dwm/
